# Generated by Django 5.0.7 on 2024-07-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sacco", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.IntegerField(unique=True),
        ),
    ]
