import axios from 'axios';

const API_BASE_URL = 'http://127.0.0.1:8000';

const api = axios.create({
    baseURL: API_BASE_URL,
});

export const getMembers = () => {
    return api.get('/api/members');  // Return the promise generated by axios.get()
};

export const getMember = (id) => {
    return api.get(`/api/members/${id}`);  // Return the promise generated by axios.get()
};

export const createMember = (data) => {
    return api.post('/members/', data);  // Return the promise generated by axios.post()
};

export const updateMember = (id, data) => {
    return api.put(`/members/${id}/`, data);  // Return the promise generated by axios.put()
};

export const deleteMember = (id) => {
    return api.delete(`/members/${id}/`);  // Return the promise generated by axios.delete()
};

export const getLoans = () => {
    return api.get('/loans/');  // Return the promise generated by axios.get()
};

export const getLoan = (id) => {
    return api.get(`/loans/${id}/`);  // Return the promise generated by axios.get()
};

export const createLoan = (data) => {
    return api.post('/loans/', data);  // Return the promise generated by axios.post()
};

export const updateLoan = (id, data) => {
    return api.put(`/loans/${id}/`, data);  // Return the promise generated by axios.put()
};

export const deleteLoan = (id) => {
    return api.delete(`/loans/${id}/`);  // Return the promise generated by axios.delete()
};

export const getTransactions = () => {
    return api.get('/transactions/');  // Return the promise generated by axios.get()
};

export const getTransaction = (id) => {
    return api.get(`/transactions/${id}/`);  // Return the promise generated by axios.get()
};

export const createTransaction = (data) => {
    return api.post('/transactions/', data);  // Return the promise generated by axios.post()
};

export const updateTransaction = (id, data) => {
    return api.put(`/transactions/${id}/`, data);  // Return the promise generated by axios.put()
};

export const deleteTransaction = (id) => {
    return api.delete(`/transactions/${id}/`);  // Return the promise generated by axios.delete()
};
